### PR TITLE
Tests for Tool-checking

### PR DESCRIPTION
**Pull request by Lewih**
This test checks the availability of the command.

In order to test the 'version greater equal than' there are multiple choices:

* https://github.com/dvershinin/lastversion
* sort --version-sort --check
* Using a python script

At the moment, the availability check has been tested on Vaughan and Hydra. (on hydra zsh is not available though)

### CODE REVIEW

**Comment by smoors** [comment]
in Easybuild, this is done with LooseVersion
```
from distutils.version import LooseVersion
LooseVersion('4.1.1-5') > LooseVersion('4.1.1')  # True
```
however, distutils will be removed in the future, so maybe better to use  this:
```
from pkg_resources import parse_version as version
version("2.1-beta") < version("2.1")  # True
```
https://majornetwork.net/2021/05/comparing-version-numbers-in-python/

**Comment by Lewih** [comment]
The availability check should now be considered stable.

There are issues during the extraction of the version numbet.

**Comment by smoors** [comment]
relative imports did not work, so I had to update `sys.path` directly.
I have not yet looked at the version check code, but parsing the version will be different for each tool. we can easily add this to the dictionaries in tools_list.py.

**Comment by Lewih** [comment]
While playing around the following issues arose:

1. not able to intercept ```module --version``` output stream, nor to pipe it, any idea?
2. ksh version output is not "standard", also from ```rpm -q```

Focusing only to software installed at system level (with exception of zsh which is not at system level in Hydra) at the moment.
For software installed as a module (throughout the entire VSC the module key can be added in the ```tools_list.py``` file)

Suggestions:
1. should we consider another optional ```tools_list.py``` field such as *regex* in order to be able to contemplate abnormal version syntax whenever necessary(e.g. ksh)? This solution would give us flexibility and avoid the definition of every single tool version case.
2. Once this is set let's move to module loaded software

**Review by Lewih — COMMENTED** [review]
LGTM

**Comment by smoors** [comment]
>should we consider another optional tools_list.py field such as regex in order to be able to contemplate abnormal version syntax whenever necessary(e.g. ksh)? This solution would give us flexibility and avoid the definition of every single tool version case.

yes, that would be the best option I think. if there is a regex that works for most outputs, we can use that by default, and add a custom regex for the tools that need it.

>not able to intercept module --version output stream, nor to pipe it, any idea?

do you have the tcl modules or lmod?

```
$ module --version

Modules based on Lua: Version 8.5.7  2021-06-25 13:59 -05:00
    by Robert McLay mclay@tacc.utexas.edu
```

(btw, you don't have to comment out the tools that do not work. it's useful to see which ones fail, so we know we either have to install it or fix the tests.)

**Comment by smoors** [comment]
>not able to intercept module --version output stream, nor to pipe it, any idea?

the problem is that it sends output to stderr, can be solved by redirecting to stdout
```
module --version 2>&1
```

**Comment by Lewih** [comment]
Added readme. Tested on Hydra an Vaughan.

**Comment by wpoely86** [comment]
Lmod sets a variable `$LMOD_VERSION` if that's helpful.

**Pull request merged**
